apiVersion: v1
kind: Service
metadata:
  name: test-sts
  labels:
    app: test-sts
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: test-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
  namespace: kopf
spec:
  serviceName: test-sts
  replicas: 1
  selector:
    matchLabels:
      app: test-sts
  template:
    metadata:
      labels:
        app: test-sts
    spec:
      containers:
        - name: hello
          image: monopole/hello:1
